spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pc_market
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 0000