spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pc_market
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
server:
  port: 8081